### ISSUE TITLE
Strange versioning of GESIS Central concepts of R|EX research

### ISSUE THREAD

**Issue by MajaDolinar** [cessda/cessda.cvs.two#654]
GESIS vocabulary https://vocabularies.cessda.eu/vocabulary/KategorienschemaWahlstudien versioning is behaving strangely. 
It should probably be SL in German and TL in English. 
As noted in https://github.com/cessda/cessda.cvs.two/issues/607#issuecomment-1541413596:
"Probably it should be originally in German, but the English was ahead so it was aligned as 1.0.2, but if we follow the new versioning paradigm, probably it should be 1.1.0."

I will ask Gesis what the SL in this case is for them and what their workflow for entering this vocabulary was.

**Comment by MajaDolinar** [comment]
I asked Gesis about their workflow in entering this vocabulary. It is as we suspected:
"The source language was German
And we followed the workflow you described below. Once we have added all the codes, we set the CV to ‘ready to publish’ and then the translation followed. After that the vocabulary was published"

Apparently, when you create a completely new vocabulary and not publish it - only put to Ready to translate status, the publication after the added translations is set to 1.0.0 and not 1.0.1 (accounting for the translations).

**Comment by pakoselo** [comment]
@MajaDolinar @Stifo probably we need to hack the database once again.

**Comment by MajaDolinar** [comment]
Before doing anything, let me first test this a bit on staging. 
The problem as I see it is that if a someone creates a completely new vocabulary in SL and only sends it to "Ready to be translated status" and not publishes it prior to that, then the translations that will be created - so the entire published package at the end will receive 1.0.0
So in this case it means that they created a new vocabulary in German (SL), put it on "Ready to be translated" status, created an English translation to it and then published it as a package. This created the version 1.0.0 which according to the rules we have means that there is only SL and no translations, however, there is an English translation included now in 1.0.0 (which should be then 1.0.1). It basically creates a confusion for the end-user and does not follow the rules we set up. 
Hope I am explaining it so that it is understandable.

**Comment by Stifo** [comment]
I'm not sure I did understand the problem either... I can't see a problem. I think it's correct. Please, let me explain my view. I've look on how the versions were created chronologically.

This is how it was before migrating to the new versioning system:

| id | item_type | language | number | status |
|--------|--------|--------|--------|--------|
| 520 | SL | de | 1.0 | PUBLISHED |
| 573 | TL | en | 1.0.1 | PUBLISHED |
| 578 | TL | en | 1.0.2 | DRAFT |

This is after migrating to the new versioning system; i.e. current status:

| id | item_type | language | number | status |
|--------|--------|--------|--------|--------|
| 520 | SL | de | 1.0 | PUBLISHED |
| 573 | TL | en | 1.0.1 | PUBLISHED |
| 578 | TL | en | 1.0.3 | DRAFT |
| 732 | SL | de | 1.0.2 | PUBLISHED |

What the version number migration did, was aligning all the published versions in a common bundle giving it a three digit number; i.e., 1.0.2, because:
a) the latest published SL was de-1.0
b) the latest published TL was en-1.0.1
c) the next available number for publishing was 1.0.2

The minor number is changed only if there is a change in SL, which was not this case. Therefore the minor number remained 1.0. The change of the en TL's version number from 1.0.2 to 1.0.3 was because this version was still a DRAFT and it couldn't be included in the 1.0.2 bundle after migration. It was set to 1.0.3 as it was being prepared for the next publication.

**Comment by MajaDolinar** [comment]
Ah I see the issue now, I was referencing the wrong vocabulary. Yes this one that you are referring to is correct, so there is no issue with https://vocabularies.cessda.eu/vocabulary/KategorienschemaWahlstudien. 

The problem is actually this vocabulary that has the issue I was explaining above:
https://vocabularies.cessda.eu/vocabulary/rexconcepts?lang=en

So sorry for the confusion in this..

**Comment by pakoselo** [comment]
@MajaDolinar @Stifo so probably it doesn't work if we create first version. So it doesn't increase the patch number if there is no Sl published. What do you think @Stifo ?

**Comment by Stifo** [comment]
https://vocabularies.cessda.eu/vocabulary/KategorienschemaWahlstudien
---
I've noticed, that the 1.0.2 bundle is missing the en TL in it. There should have been a copy of the published en TL 1.0.1 put in the 1.0.2 bundle. I should look, whether there are more such cases in other vocabularies.

https://vocabularies.cessda.eu/vocabulary/rexconcepts?lang=en
---
please correct me, but at the time of implementing the new versioning system, there was no such explicit rule that 1.0.0 means "SL alone in the bundle". therefore, 1.0.0 could have also TLs included.

**Comment by MajaDolinar** [comment]
Yes, please create a for the Kategorienshcema Wahlstudien. 

For the Rex Concepts and all future CVs with this workflow, it should be fixed to forcing a double publish:
1. publish only the SL with 1.0.0
2. publish the translation(s), increasing the versioning to 1.0.1

**Comment by MajaDolinar** [comment]
Closing, resolved.

**Comment by Stifo** [comment]
Apparently, the fixing SQL script:

https://github.com/cessda/cessda.cvs.two/issues/654#issuecomment-1561192390

was not executed over the production database and the problem still persists there. In the dev, it is fixed.

@matthew-morris-cessda: could you please run it in the prod? please, make a backup first. thanks.

**Comment by Stifo** [comment]
thanks @matthew-morris-cessda !
